# Generated by Django 4.1.3 on 2022-11-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recidencia',
            name='nu_recidencia',
            field=models.CharField(max_length=20),
        ),
    ]
