# Generated by Django 4.1.3 on 2022-11-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_recidencia_nu_recidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recidencia',
            name='nu_recidencia',
            field=models.IntegerField(),
        ),
    ]
