# Generated by Django 4.1.3 on 2022-11-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_recidencia_nu_recidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='correo',
            name='Tipo_correo',
            field=models.CharField(choices=[('caja', 'paquete'), ('correo', 'carta')], default='correo', max_length=20),
        ),
    ]
