# Generated by Django 4.1.3 on 2022-11-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_correo_tipo_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correo',
            name='Tipo_correo',
            field=models.CharField(choices=[('caja', 'paquete'), ('correo', 'documentos')], default='correo', max_length=20),
        ),
    ]
