# Generated by Django 4.1.3 on 2022-11-14 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_correo_tipo_correo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='correo',
            new_name='correos_varios',
        ),
    ]
