# Generated by Django 4.1.3 on 2022-11-14 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_correo_correos_varios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='correos_varios',
            new_name='correos_varioss',
        ),
    ]
