# Generated by Django 4.1.3 on 2022-11-14 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_correos_varios_correos_varioss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='correos_varioss',
            new_name='correos_varios',
        ),
    ]
